model:
    family: mlp
    n_embd: 1024
    n_layer: 5
    n_head: 8
    n_dims: 10
    n_positions: 21

training:
    resume_id: 12July_mlp_10dim_5layer_1024_RL
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 10, 'end': 10, 'inc': 1, 'interval': 2000}
        points: {'start': 21, 'end': 21, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 12July_mlp_10dim_5layer_1024_RL
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
