model:
    family: lstm
    n_embd: 512
    n_layer: 5
    n_head: 8
    n_dims: 20
    n_positions: 101
    p_dropout: 0.1

training:
    resume_id: 14Aug_30points_lstm_20dim_5layer_512_lr0.0001_dropout0.1_curriculumTrue
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 5, 'end': 20, 'inc': 1, 'interval': 2000}
        points: {'start': 11, 'end': 31, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 14Aug_30points_lstm_20dim_5layer_512_lr0.0001_dropout0.1_curriculumTrue
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
