model:
    family: lstm
    n_embd: 256
    n_layer: 5
    n_head: 8
    n_dims: 3
    n_positions: 16

training:
    resume_id: 24July_lstm_3dim_5layer_256_RL
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 3, 'end': 3, 'inc': 1, 'interval': 2000}
        points: {'start': 16, 'end': 16, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 24July_lstm_3dim_5layer_256_RL
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
