model:
    family: lstm
    n_embd: 512
    n_layer: 5
    n_head: 8
    n_dims: 20
    n_positions: 101
    p_dropout: 0.1
    has_p_embedding: False
    has_layer_norm: False

training:
    resume_id: 31Aug_10layer_LayerNormF_run4_lstm_20dim_5layer_512_lr0.0001_dropout0.1_curriculumFalse_p_embeddingFalse_layernormFalse
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 20, 'end': 20, 'inc': 1, 'interval': 2000}
        points: {'start': 41, 'end': 41, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 31Aug_10layer_LayerNormF_run4_lstm_20dim_5layer_512_lr0.0001_dropout0.1_curriculumFalse_p_embeddingFalse_layernormFalse
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
