model:
    family: lstm
    n_embd: 256
    n_layer: 1
    n_head: 8
    n_dims: 3
    n_positions: 31
    p_dropout: 0.1

training:
    resume_id: 6Augtest_moreincontextexample_lstm_3dim_1layer_256_lr1e-4_dropout0.1
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 3, 'end': 3, 'inc': 1, 'interval': 2000}
        points: {'start': 31, 'end': 31, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 6Augtest_moreincontextexample_lstm_3dim_1layer_256_lr1e-4_dropout0.1
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
