model:
    family: lstm
    n_embd: 256
    n_layer: 9
    n_head: 8
    n_dims: 20
    n_positions: 101
    p_dropout: 0.1

training:
    resume_id: 6Aug_lstm_20dim_9layer_256_lr1e-4_dropout0.1
    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims: {'start': 20, 'end': 20, 'inc': 1, 'interval': 2000}
        points: {'start': 101, 'end': 101, 'inc': 2, 'interval': 2000}

out_dir: ../models/linear_regression

wandb:
    name: 6Aug_lstm_20dim_9layer_256_lr1e-4_dropout0.1
    project: in-context-training
    entity: tianqi_chen
    notes: 
    log_every_steps: 1000
