model:
    family: mlp
    n_embd: 256
    n_layer: 4
    n_head: 8 # do not need if model is mlp

    n_dims: 5
    n_positions: 11


training:
    # resume_id: gpt_dim10_l12 # use for run_id and in the folder name

    task: linear_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 10 #originally 64
    learning_rate: 0.0001 #originally 0.0001
    save_every_steps: 100 #originally 1000
    keep_every_steps: 100000
    train_steps: 501 
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 11
            inc: 2
            interval: 2000

out_dir: ../models/linear_regression

wandb:
    name: "test"
    project: in-context-training
    entity: tianqi_chen
    notes:
    log_every_steps: 100
